baseURL: 'https://awainverse.github.io/asl-nam-2026'
languageCode: 'en-us'
title: 'ASL NA Meeting 2026'
copyright: "Â© 2025, ASL and 2026 Organizers"
theme: PaperMod

params:
  author: ""
  description: Description
  defaultTheme: light
  disableThemeToggle: false

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

markup:
    goldmark:
        parser:
          attribute:
            block: true
        renderer:
            unsafe: true

menu:
    main:
        - name: Poster
          url: asl_poster.pdf
          weight: 7